// SPDX-License-Identifier: AGPL-3.0-or-later
// La pàgina en castellà (ADR 0025): les traduccions dels textos que comu.js i
// casa.js passen per T (la clau és el text català, amb {0}, {1}… on van els
// valors) i de les paraules que venen a les dades (TD). Es carrega abans que
// comu.js. Si a la pàgina s'hi afegeix o s'hi canvia un text, les proves
// avisen que aquí falta.

// «hasta el viernes», però «hasta mañana».
function ambArticle(dia) {
  return dia === 'hoy' || dia === 'mañana' ? dia : `el ${dia}`;
}

var IDIOMA = {
  codi: 'es',
  textos: {
    'Es preveu un risc a mitjà termini. El pla no està activat: només cal estar-ne pendent.': 'Se prevé un riesgo a medio plazo. El plan no está activado: solo hay que estar pendiente.',
    'El pla està activat: es preveu un risc important a curt termini, o hi ha afectacions que no són greus.': 'El plan está activado: se prevé un riesgo importante a corto plazo, o hay afectaciones que no son graves.',
    'El pla està activat per un risc greu per a la població: segueix les indicacions de Protecció Civil.': 'El plan está activado por un riesgo grave para la población: sigue las indicaciones de Protección Civil.',
    'Què vol dir {0}?': '¿Qué quiere decir {0}?',
    'Tanca': 'Cerrar',
    "Nou!": "¡Nuevo!",
    "Situacions de perill": "Situaciones de peligro",
    "Desbordament de la riera de Sant Cugat (en proves)": "Desbordamiento de la riera de Sant Cugat (en pruebas)",
    "Pluja a punt de començar (15 min abans)": "Lluvia a punto de empezar (15 min antes)",
    "6 h": "6 h",
    "7 h": "7 h",
    "8 h": "8 h",
    "Demanant permís…": "Pidiendo permiso…",
    "El navegador té bloquejades les notificacions d\u2019aquesta web. Permet-les a la configuració del navegador (al cadenat, al costat de l\u2019adreça) i torna-ho a provar.": "El navegador tiene bloqueadas las notificaciones de esta web. Permítelas en la configuración del navegador (en el candado, junto a la dirección) y vuelve a probarlo.",
    "Fet: els avisos que has triat t\u2019arribaran a aquest dispositiu. Pots enviar-te una prova.": "Hecho: los avisos que has elegido te llegarán a este dispositivo. Puedes enviarte una prueba.",
    "No s\u2019han pogut activar els avisos. Torna-ho a provar d\u2019aquí a una estona.": "No se han podido activar los avisos. Vuelve a probarlo dentro de un rato.",
    "Avisos desactivats en aquest dispositiu: ja no se\u2019n desa res.": "Avisos desactivados en este dispositivo: ya no se guarda nada.",
    "D\u2019aquí a un minut t\u2019ha d\u2019arribar una notificació de prova.": "Dentro de un minuto te tiene que llegar una notificación de prueba.",
    "No s\u2019ha pogut demanar la prova. Torna-ho a provar d\u2019aquí a una estona.": "No se ha podido pedir la prueba. Vuelve a probarlo dentro de un rato.",
    "Què vols rebre": "Qué quieres recibir",
    "Envia\u2019m una prova": "Envíame una prueba",
    "Desactiva": "Desactivar",
    "Activa els avisos": "Activar los avisos",
    "Avisos activats en aquest dispositiu. Si canvies què reps, es desa sol.": "Avisos activados en este dispositivo. Si cambias qué recibes, se guarda solo.",
    "Tria què vols rebre i toca «Activa els avisos». El navegador et demanarà permís.": "Elige qué quieres recibir y toca «Activar los avisos». El navegador te pedirá permiso.",
    "Ara no es pot connectar amb el servidor dels avisos. Torna-ho a provar d\u2019aquí a una estona.": "Ahora no se puede conectar con el servidor de los avisos. Vuelve a probarlo dentro de un rato.",
    "Desat a les {0}.": "Guardado a las {0}.",
    "No s\u2019ha pogut desar el canvi. Torna-ho a provar d\u2019aquí a una estona.": "No se ha podido guardar el cambio. Vuelve a probarlo dentro de un rato.",
    "Les dades són de les {0}: fa més de {1} hores que no s\u2019actualitzen. La previsió i l\u2019estat dels trens no es mostren fins que tornin.": "Los datos son de las {0}: hace más de {1} horas que no se actualizan. La previsión y el estado de los trenes no se muestran hasta que vuelvan.",
    "Mentrestant: ": "Mientras tanto: ",
    "Dades del servidor de reserva.": "Datos del servidor de reserva.",
    "previsió de Meteocat": "previsión de Meteocat",
    "radar": "radar",
    "Mode normal": "Modo normal", "Mode vigilància": "Modo vigilancia",
    "Què vol dir el mode?": "¿Qué significa el modo?",
    "Mode normal: la pàgina s’actualitza cada {0} minuts. Mode vigilància: s’actualitza cada {1} minuts, just després de cada imatge nova del radar de Meteocat. La pàgina es posa en mode vigilància quan hi ha un avís de l’AEMET, un pla de Protecció Civil en alerta o emergència, pluja a Montflorit o pluja al radar a menys de {2} km. Quan ja no hi ha res d’això, torna al mode normal.": "Modo normal: la página se actualiza cada {0} minutos. Modo vigilancia: se actualiza cada {1} minutos, justo después de cada imagen nueva del radar de Meteocat. La página se pone en modo vigilancia cuando hay un aviso de AEMET, un plan de Protección Civil en alerta o emergencia, lluvia en Montflorit o lluvia en el radar a menos de {2} km. Cuando ya no hay nada de eso, vuelve al modo normal.",
    " del {0}": " del {0}",
    "demà a les {0}": "mañana a las {0}",
    "L’actualització de les {0} no s’ha fet: les dades són de les {1}.": "La actualización de las {0} no se ha hecho: los datos son de las {1}.",
    "a la {0}": "a la {0}",
    "a les {0}": "a las {0}",
    "avui fins {0}":
      (hora) => `hoy hasta ${hora.replace(/^a /, '')}`,
    "fins {0} {1}":
      (dia, hora) => `hasta ${ambArticle(dia)} ${hora}`,
    "d’{0}": "de {0}",
    "de {0}": "de {0}",
    "{0} {1} fins {2} {3}":
      (dia, de, diaFi, hora) => `${dia} ${de} hasta ${ambArticle(diaFi)} ${hora}`,
    "a {0}": "a {0}",
    "Avís {0} de l\u2019AEMET per {1} al Vallès": "Aviso {0} de la AEMET por {1} en el Vallès",
    "Open-Meteo, d’on surten els models, ara no respon: la previsió és la de les {0}{1}.": "Open-Meteo, de donde salen los modelos, ahora no responde: la previsión es la de las {0}{1}.",
    "Protecció Civil: pla {0} ({1}) en fase {2}.": "Protección Civil: plan {0} ({1}) en fase {2}.",
    "versió {0}": "versión {0}",
    " i ": " y ",
    "Actualitzat a les ": "Actualizado a las ",
    " · propera: ": " · próxima: ",
    "No s’han pogut llegir totes les fonts: la informació és menys segura.": "No se han podido leer todas las fuentes: la información es menos segura.",
    "avui": "hoy",
    "demà": "mañana",
    "a mitjanit": "a medianoche",
    "Avís de Protecció Civil": "Aviso de Protección Civil",
    "El consell de cada mitjà surt del temps previst i del trànsit: no té en compte l’emergència de Protecció Civil (vegeu l’avís de dalt).": "El consejo de cada medio sale del tiempo previsto y del tráfico: no tiene en cuenta la emergencia de Protección Civil (véase el aviso de arriba).",
    "El consell de cada mitjà surt del temps previst i del trànsit: no té en compte l’alerta de Protecció Civil (vegeu l’avís de dalt).": "El consejo de cada medio sale del tiempo previsto y del tráfico: no tiene en cuenta la alerta de Protección Civil (véase el aviso de arriba).",
    "Són els trens d’ara, no els de l’hora triada.": "Son los trenes de ahora, no los de la hora elegida.",
    " Evita els desplaçaments que no siguin necessaris.": " Evita los desplazamientos que no sean necesarios.",
    "Comunicat (PDF)": "Comunicado (PDF)",
    "Pressió {0}\u00a0hPa": "Presión {0}\u00a0hPa",
    "{0}, estable": "{0}, estable",
    "{0}, {1}{2} ({3}{4} en 3\u00a0h)": "{0}, {1}{2} ({3}{4} en 3\u00a0h)",
    "El temps ara a {0}": "El tiempo ahora en {0}",
    "Ara a {0} ({1})": "Ahora en {0} ({1})",
    "Plou: {0} mm/h": "Llueve: {0} mm/h",
    "{0} mm avui": "{0} mm hoy",
    "Humitat {0} %": "Humedad {0} %",
    "Vent {0} km/h{1}, {2} {3}": "Viento {0} km/h{1}, {2} {3}",
    " (ratxes de {0})": " (rachas de {0})",
    "estacions veïnes": "estaciones vecinas",
    "Arribaria pluja cap a les\u00a0{0}": "Llegaría lluvia hacia las\u00a0{0}",
    "Pot arribar pluja cap a les\u00a0{0}": "Puede llegar lluvia hacia las\u00a0{0}",
    " · va cap {0} a {1}\u00a0km/h": " · va hacia {0} a {1}\u00a0km/h",
    "Radar de {0} de les {1}{2}": "Radar de {0} de las {1}{2}",
    "Risc {0}": "Riesgo {0}",
    "(llindar {0} de l’AEMET: {1} {2})": "(umbral {0} de la AEMET: {1} {2})",
    "Avís {0} de l’AEMET per {1}": "Aviso {0} de la AEMET por {1}",
    "Avís {0} · {1}": "Aviso {0} · {1}",
    "Avís {0}": "Aviso {0}",
    "Probabilitat de pluja apresa del que ha plogut de veritat a {0} des del {1}, quan els models deien el mateix.": "Probabilidad de lluvia aprendida de lo que ha llovido de verdad en {0} desde el {1}, cuando los modelos decían lo mismo.",
    "Probabilitat de pluja apresa del que va ploure de veritat a Sabadell i Sant Cugat des del {0}, quan els models deien el mateix.": "Probabilidad de lluvia aprendida de lo que llovió de verdad en Sabadell y Sant Cugat desde {0}, cuando los modelos decían lo mismo.",
    " Temperatura corregida amb el que ha mesurat {0} des del {1}.": " Temperatura corregida con lo que ha medido {0} desde el {1}.",
    " Temperatura corregida amb el registre propi de {0} des del {1}.": " Temperatura corregida con el registro propio de {0} desde el {1}.",
    "Avui els models no veuen aquesta pluja: en les darreres {0} hores han caigut {1}\u00a0mm a Montflorit i en preveien {2}. Les primeres hores de la taula parteixen del que mesura l’estació; per a la resta, fes més cas dels avisos.": "Hoy los modelos no ven esta lluvia: en las últimas {0} horas han caído {1}\u00a0mm en Montflorit y preveían {2}. Las primeras horas de la tabla parten de lo que mide la estación; para el resto, haz más caso de los avisos.",
    "Tempesta": "Tormenta",
    "Tempesta amb calamarsa": "Tormenta con granizo",
    "Pluja torrencial": "Lluvia torrencial",
    "Pluja forta": "Lluvia fuerte",
    "Pluja moderada": "Lluvia moderada",
    "Pluja feble": "Lluvia débil",
    "Pluja gelant": "Lluvia engelante",
    "Neu forta": "Nieve fuerte", "Neu moderada": "Nieve moderada", "Neu feble": "Nieve débil",
    "Possible tempesta": "Posible tormenta",
    "Possible pluja": "Posible lluvia",
    "Possible neu": "Posible nieve",
    "Pluja": "Lluvia", "Neu": "Nieve",
    "Boira": "Niebla",
    "Serè": "Despejado",
    "Poc ennuvolat": "Poco nuboso",
    "Mig ennuvolat": "Nuboso",
    "Molt ennuvolat": "Muy nuboso",
    "Cobert": "Cubierto",
    "pujant": "subiendo",
    "baixant": "bajando",
    " ràpid": " rápido",
    "No plou": "No llueve",
    "semblant a ahir": "similar a ayer",
    "semblant a avui": "similar a hoy",
    "{0}° més que ahir": "{0}° más que ayer",
    "{0}° menys que ahir": "{0}° menos que ayer",
    "{0}° més que avui": "{0}° más que hoy",
    "{0}° menys que avui": "{0}° menos que hoy",
    "Plou en una estació veïna": "Llueve en una estación vecina",
    "Pluja a sobre": "Lluvia encima",
    " · pararia cap a les\u00a0{0}": " · pararía hacia las\u00a0{0}",
    " · no s\u2019acaba en 2 hores": " · no acaba en 2 horas",
    " (en entrenament)": " (en entrenamiento)",
    "Hora estimada amb el radar. Encara s\u2019està entrenant amb la pluja real: pot fallar.": "Hora estimada con el radar. Todavía se está entrenando con la lluvia real: puede fallar.",
    "Pluja a prop: pot arribar": "Lluvia cerca: puede llegar",
    "No s’acosta pluja en 2 hores": "No se acerca lluvia en 2 horas",
    "Risc previst": "Riesgo previsto",
    "Avís": "Aviso",
    "Previsió": "Previsión", "Desplega-ho tot": "Desplegar todo", "Plega-ho tot": "Plegar todo",
    "Més enllà de les 24 hores la previsió és menys precisa: alguns models no hi arriben i la probabilitat apresa és la d\u2019un dia abans.": "Más allá de las 24 horas la previsión es menos precisa: algunos modelos no llegan y la probabilidad aprendida es la de un día antes.",
    "Hora": "Hora",
    "Avisos": "Avisos",
    "Cel": "Cielo",
    "Pluja (mm)": "Lluvia (mm)",
    "Prob.": "Prob.",
    "Vent": "Viento",
    "Plou ara": "Llueve ahora",
    "* Segons la pluja que mesura ara l’estació i el que va passar en casos semblants a Sabadell i Sant Cugat entre el 2024 i el 2026.": "* Según la lluvia que mide ahora la estación y lo que pasó en casos parecidos en Sabadell y Sant Cugat entre 2024 y 2026.",
    "† Segons el radar: la pluja que hi ha ara, portada endavant a la velocitat i en la direcció que porta.": "† Según el radar: la lluvia que hay ahora, llevada hacia delante a la velocidad y en la dirección que lleva.",
    "La barra de color al costat de l’hora marca les hores amb avís de l’AEMET, del color del nivell.": "La barra de color junto a la hora marca las horas con aviso de la AEMET, del color del nivel.",
    "Vent en km/h: mitjana i, entre parèntesis, les ratxes.": "Viento en km/h: media y, entre paréntesis, las rachas.",
    "No s’ha pogut carregar la previsió. Torna-ho a provar d’aquí a una estona.": "No se ha podido cargar la previsión. Vuelve a probarlo dentro de un rato.",
    // «Si surts» (ADR 0029).
    "a l\u2019anada ({0}\u00a0h)": "a la ida ({0}\u00a0h)",
    "a la tornada ({0}\u00a0h)": "a la vuelta ({0}\u00a0h)",
    "a l\u2019anada i a la tornada": "a la ida y a la vuelta",
    "Pluja probable {0}.": "Lluvia probable {0}.",
    "Pot ploure {0}: porta l\u2019impermeable.": "Puede llover {0}: lleva el impermeable.",
    "Pot ploure {0}.": "Puede llover {0}.",
    "Ratxes de vent de fins a {0}\u00a0km/h.": "Rachas de viento de hasta {0}\u00a0km/h.",
    "{0}: hi pot haver gel.": "{0}: puede haber hielo.",
    "{0}: compte amb el gel a primera hora.": "{0}: cuidado con el hielo a primera hora.",
    "Trens: {0}.": "Trenes: {0}.",
    "A {0}\u00a0km/h, {1} es noten com {2}.": "A {0}\u00a0km/h, {1} se notan como {2}.",
    "A la tornada ({0}\u00a0h, {1}): {2}": "A la vuelta ({0}\u00a0h, {1}): {2}",
    "Amb vent de {0}\u00a0km/h, {1} es noten com {2}.": "Con viento de {0}\u00a0km/h, {1} se notan como {2}.",
    "A partir de les {0}\u00a0h, risc de pluja.": "A partir de las {0}\u00a0h, riesgo de lluvia.",
    "Cap a les {0}\u00a0h s\u2019acaba el risc de pluja.": "Hacia las {0}\u00a0h se acaba el riesgo de lluvia.",
    "La temperatura va de {0} ({1}\u00a0h) a {2} ({3}\u00a0h).": "La temperatura va de {0} ({1}\u00a0h) a {2} ({3}\u00a0h).",
    "Calor: fins a {0}. Porta aigua i evita el sol de les hores centrals.": "Calor: hasta {0}. Lleva agua y evita el sol de las horas centrales.",
    "Protector solar, gorra i ulleres de sol: índex UV {0} ({1}) cap a les {2}\u00a0h.": "Protector solar, gorra y gafas de sol: índice UV {0} ({1}) hacia las {2}\u00a0h.",
    "demà {0}": "mañana {0}",
    "Roba: {0}": "Ropa: {0}",
    "Dades de Renfe i d\u2019FGC de les {0}, consultades automàticament: l\u2019autor no es fa responsable de la seva exactitud.": "Datos de Renfe y de FGC de las {0}, consultados automáticamente: el autor no se hace responsable de su exactitud.",
    "Pot ploure mentre ets fora: porta paraigua.": "Puede llover mientras estás fuera: lleva paraguas.",
    "Avís de l\u2019AEMET per pluja mentre ets fora: ni el radar, ni les estacions, ni els models hi veuen pluja. Per si de cas, porta paraigua.": "Aviso de la AEMET por lluvia mientras estás fuera: ni el radar, ni las estaciones, ni los modelos ven lluvia. Por si acaso, lleva paraguas.",
    "Avís de l\u2019AEMET per pluja {0}: ni el radar, ni les estacions, ni els models hi veuen pluja.": "Aviso de la AEMET por lluvia {0}: ni el radar, ni las estaciones, ni los modelos ven lluvia.",
    "Avís de l\u2019AEMET per pluja {0}: ni el radar, ni les estacions, ni els models hi veuen pluja. Per si de cas, porta l\u2019impermeable.": "Aviso de la AEMET por lluvia {0}: ni el radar, ni las estaciones, ni los modelos ven lluvia. Por si acaso, lleva el impermeable.",
    "A partir de les {0}\u00a0h, avís de l\u2019AEMET per pluja.": "A partir de las {0}\u00a0h, aviso de la AEMET por lluvia.",
    "Cap a les {0}\u00a0h s\u2019acaba l\u2019avís de l\u2019AEMET.": "Hacia las {0}\u00a0h se acaba el aviso de la AEMET.",
    "Sense pluja ni vent fort.": "Sin lluvia ni viento fuerte.",
    "Avisos actius": "Avisos activos",
    "Mapa": "Mapa",
    ", a {0}\u00a0km de Montflorit": ", a {0}\u00a0km de Montflorit",
    "Bombers: incendi forestal a {0}": "Bombers: incendio forestal en {0}",
    "{0}, des de les {1}.": "{0}, desde las {1}.",
    "Pla Alfa de Cerdanyola: nivell {0} {1}": "Plan Alfa de Cerdanyola: nivel {0} {1}",
    ": accés restringit als espais forestals.": ": acceso restringido a los espacios forestales.",
    "Agents Rurals: tancat {0}": "Agents Rurals: cerrado {0}",
    "avui": "hoy", "demà": "mañana",
    "Com es llegeix la taula": "Cómo se lee la tabla",
    "Matí": "Mañana", "Tarda": "Tarde", "Nit": "Noche",
    "Demà matí": "Mañana por la mañana", "Demà tarda": "Mañana por la tarde", "Demà nit": "Mañana por la noche",
    "fins a les {0} h": "hasta las {0} h",
    ", uns {0} mm": ", unos {0} mm",
    "tempesta": "tormenta", "pluja forta": "lluvia fuerte", "pluja torrencial": "lluvia torrencial", "neu": "nieve", "calor": "calor", "glaçada": "helada",
    "ratxes de {0}\u00a0km/h": "rachas de {0}\u00a0km/h",
    "{0} sense incidències; de {1} ara no hi ha dades.": "{0} sin incidencias; de {1} ahora no hay datos.",
    "De {0} ara no hi ha dades.": "De {0} ahora no hay datos.",
    "Fins a {0}\u00a0mm de pluja en una hora {1}: millor no agafar el cotxe.": "Hasta {0}\u00a0mm de lluvia en una hora {1}: mejor no coger el coche.",
    "Fins a {0}\u00a0mm de pluja en una hora {1}: condueix amb compte.": "Hasta {0}\u00a0mm de lluvia en una hora {1}: conduce con cuidado.",
    "Pluja probable {0}: condueix amb compte.": "Lluvia probable {0}: conduce con cuidado.",
    "Pot ploure {0}: condueix amb compte.": "Puede llover {0}: conduce con cuidado.",
    "Avís de l\u2019AEMET per pluja {0}: ni el radar, ni les estacions, ni els models hi veuen pluja. Condueix amb compte.": "Aviso de la AEMET por lluvia {0}: ni el radar, ni las estaciones, ni los modelos ven lluvia. Conduce con cuidado.",
    "Roba de moto d\u2019hivern tèrmica, guants d\u2019hivern i tub de coll.": "Ropa de moto de invierno térmica, guantes de invierno y braga de cuello.",
    "Jaqueta de moto d\u2019hivern, guants d\u2019hivern i tub de coll.": "Chaqueta de moto de invierno, guantes de invierno y braga de cuello.",
    "Jaqueta de moto amb folre i guants d\u2019entretemps.": "Chaqueta de moto con forro y guantes de entretiempo.",
    "Jaqueta de moto de mitja temporada i guants d\u2019entretemps.": "Chaqueta de moto de media temporada y guantes de entretiempo.",
    "Jaqueta de moto d\u2019estiu, ventilada, i guants d\u2019estiu.": "Chaqueta de moto de verano, ventilada, y guantes de verano.",
    "Jaqueta d\u2019abric, guants i tub de coll.": "Chaqueta de abrigo, guantes y braga de cuello.",
    "Jaqueta tallavent amb una capa a sota, i guants.": "Chaqueta cortavientos con una capa debajo, y guantes.",
    "Jaqueta tallavent lleugera.": "Chaqueta cortavientos ligera.",
    "Màniga llarga o una jaqueta molt lleugera.": "Manga larga o una chaqueta muy ligera.",
    "Màniga curta.": "Manga corta.",
    "Màniga curta o màniga llarga fina.": "Manga corta o manga larga fina.",
    "Màniga llarga o jersei fi.": "Manga larga o jersey fino.",
    "Abric, gorro, bufanda i guants.": "Abrigo, gorro, bufanda y guantes.",
    "Abric, bufanda i guants.": "Abrigo, bufanda y guantes.",
    "Abric.": "Abrigo.",
    "Jaqueta.": "Chaqueta.",
    "Jaqueta lleugera o jersei.": "Chaqueta ligera o jersey.",
    "Impermeable.": "Impermeable.",
    "Surts i tornes de nit: a peu, en bici o en patinet, roba visible i llum.": "Sales y vuelves de noche: a pie, en bici o en patinete, ropa visible y luz.",
    "Surts de nit: a peu, en bici o en patinet, roba visible i llum.": "Sales de noche: a pie, en bici o en patinete, ropa visible y luz.",
    "Tornaràs de nit: a peu, en bici o en patinet, roba visible i llum.": "Volverás de noche: a pie, en bici o en patinete, ropa visible y luz.",
    "Ara": "Ahora",
    "Ara no hi ha previsió hora a hora.": "Ahora no hay previsión hora a hora.",
    "Avís d\u2019FGC": "Aviso de FGC",
    "Avís de Rodalies": "Aviso de Rodalies",
    "Rodalies diu que hi ha circulació ferroviària, però a l\u2019última hora no s\u2019ha vist cap tren a prop de l\u2019estació.": "Rodalies dice que hay circulación ferroviaria, pero en la última hora no se ha visto ningún tren cerca de la estación.",
    "FGC diu que hi ha circulació, però a l\u2019última hora no s\u2019ha vist cap tren a prop de l\u2019estació.": "FGC dice que hay circulación, pero en la última hora no se ha visto ningún tren cerca de la estación.",
    "Estat del servei: ": "Estado del servicio: ",
    "Busos de l\u2019AMB": "Autobuses de la AMB",
    "Estat de cada línia": "Estado de cada línea",
    "Tria a dalt els mitjans que vols veure.": "Elige arriba los medios que quieres ver.",
    "Toca un mitjà per deixar de veure\u2019l; torna-hi a tocar per recuperar-lo. Es recorda en aquest dispositiu.": "Toca un medio para dejar de verlo; vuelve a tocarlo para recuperarlo. Se recuerda en este dispositivo.",
    "A aquesta hora no circulen trens.": "A esta hora no circulan trenes.",
    "Ara no hi ha dades dels trens.": "Ahora no hay datos de los trenes.",
    "Cap incidència als trens de Cerdanyola.": "Ninguna incidencia en los trenes de Cerdanyola.",
    "Avui": "Hoy",
    "Demà": "Mañana",
    "Trens": "Trenes",
    "Trànsit": "Tráfico",
    "Cap": "Ninguna",
    "Previsió del dia, al matí, a les:": "Previsión del día, por la mañana, a las:",
    "A les 21 h, la previsió de demà": "A las 21 h, la previsión de mañana",
    "Sol": "Sol",
    "Aire": "Aire",
    "Pol·len": "Polen",
    "Nul": "Nulo",
    "Baix": "Bajo",
    "Mig": "Medio",
    "Alt": "Alto",
    "Màxim": "Máximo",
    "En augment": "En aumento",
    "En descens": "En descenso",
    "Situació excepcional": "Situación excepcional",
    "{0}: nivell nul.": "{0}: nivel nulo.",
    "Pol·len a Bellaterra": "Polen en Bellaterra",
    " (setmana del {0} al {1}, a {2} km)": " (semana del {0} al {1}, a {2} km)",
    "Són les dades de l\u2019última setmana publicada.": "Son los datos de la última semana publicada.",
    "Espores de fongs": "Esporas de hongos",
    "Bona": "Buena",
    "Raonablement bona": "Razonablemente buena",
    "Regular": "Regular",
    "Desfavorable": "Desfavorable",
    "Molt desfavorable": "Muy desfavorable",
    "Extremadament desfavorable": "Extremadamente desfavorable",
    "Partícules fines (PM2,5)": "Partículas finas (PM2,5)",
    "Partícules (PM10)": "Partículas (PM10)",
    "Diòxid de nitrogen (NO₂)": "Dióxido de nitrógeno (NO₂)",
    "Ozó (O₃)": "Ozono (O₃)",
    "Diòxid de sofre (SO₂)": "Dióxido de azufre (SO₂)",
    "Qualitat de l\u2019aire a Montflorit": "Calidad del aire en Montflorit",
    "índex europeu {0}": "índice europeo {0}",
    "Per contaminant": "Por contaminante",
    "La resta del dia": "El resto del día",
    "El pitjor moment: {0} cap a les {1}.": "El peor momento: {0} hacia las {1}.",
    "Mesures de les estacions (Generalitat)": "Medidas de las estaciones (Generalitat)",
    "Estimació del model europeu CAMS per a una zona d\u2019uns 10 km al voltant de Bellaterra, no mesurada a Montflorit": "Estimación del modelo europeo CAMS para una zona de unos 10 km alrededor de Bellaterra, no medida en Montflorit",
    "; {0}, corregits amb les mesures de les estacions dels últims 30 dies.": "; {0}, corregidos con las medidas de las estaciones de los últimos 30 días.",
    "ozó": "ozono",
    "i": "y",
    "El sol avui a Montflorit": "El sol hoy en Montflorit",
    "{0} h {1} min de llum.": "{0} h {1} min de luz.",
    "UV {0}": "UV {0}",
    "Índex UV màxim {0}.": "Índice UV máximo {0}.",
    "baix": "bajo",
    "moderat": "moderado",
    "alt": "alto",
    "molt alt": "muy alto",
    "extrem": "extremo",
    "A les hores centrals, protector solar, gorra i ulleres de sol.": "A las horas centrales, protector solar, gorra y gafas de sol.",
    "Demà surt a les {0} i es pon a les {1}.": "Mañana sale a las {0} y se pone a las {1}.",
    "Hores de llum: de {0} a {1}": "Horas de luz: de {0} a {1}",
    "ara": "ahora",
    "Surt a les {0} i es pon a les {1}.": "Sale a las {0} y se pone a las {1}.",
    "Cap incidència a menys de 5\u00a0km de Montflorit.": "Ninguna incidencia a menos de 5\u00a0km de Montflorit.",
    "Trens de Cerdanyola": "Trenes de Cerdanyola",
    "Trànsit a menys de 5\u00a0km de Montflorit": "Tráfico a menos de 5\u00a0km de Montflorit",
    "Ara aquesta consulta no està disponible.": "Ahora esta consulta no está disponible.",
    "Ara hi ha retencions o talls a menys de 5\u00a0km: {0}.": "Ahora hay retenciones o cortes a menos de 5\u00a0km: {0}.",
    "Trànsit ara: 1 incidència a menys de 5\u00a0km": "Tráfico ahora: 1 incidencia a menos de 5\u00a0km",
    "Trànsit ara: {0} incidències a menys de 5\u00a0km": "Tráfico ahora: {0} incidencias a menos de 5\u00a0km",
    "Trànsit ara: cap incidència a menys de 5\u00a0km.": "Tráfico ahora: ninguna incidencia a menos de 5\u00a0km.",
    "Obres: {0}": "Obras: {0}",
    "km {0}": "km {0}",
    "a {0}": "a {0}",
    "Dades del Servei Català de Trànsit de les {0}, consultades automàticament: l\u2019autor no es fa responsable de la seva exactitud.": "Datos del Servei Català de Trànsit de las {0}, consultados automáticamente: el autor no se hace responsable de su exactitud.",
    "Estat del trànsit: ": "Estado del tráfico: ",
  },
  // Paraules que venen a les dades: nivells, tipus d'avís, plans i rumbs.
  dades: {
    groc: 'amarillo', taronja: 'naranja', vermell: 'rojo',
    // Els motius del mode vigilància (prevision.motivos_modo_aviso).
    "avís de l'AEMET": 'aviso de AEMET', 'pla de Protecció Civil': 'plan de Protección Civil',
    'pluja a les estacions': 'lluvia en las estaciones', 'pluja al radar': 'lluvia en el radar',
    pluja: 'lluvia', tempestes: 'tormentas',
    "d'inundacions": 'de inundaciones', 'de vent': 'de viento', 'de neu': 'de nieve',
    'per onada de calor': 'por ola de calor', 'per onada de fred': 'por ola de frío',
    'per contaminació': 'por contaminación', 'per vent': 'por viento',
    prealerta: 'prealerta', alerta: 'alerta', 'emergència': 'emergencia',
    'al nord': 'el norte', 'al nord-est': 'el nordeste', "a l'est": 'el este', 'al sud-est': 'el sudeste',
    'al sud': 'el sur', 'al sud-oest': 'el sudoeste', "a l'oest": 'el oeste', 'al nord-oest': 'el noroeste',
    // «Si surts»: mitjans, veredictes, estat dels trens i índex UV.
    "A peu": "A pie",
    "Bici o patinet": "Bici o patinete",
    "Moto": "Moto",
    "Cotxe": "Coche",
    "Transport públic": "Transporte público",
    "Bé": "Bien",
    "Compte": "Cuidado",
    "Millor no": "Mejor no",
    "Amb incidències": "Con incidencias",
    "Sense incidències": "Sin incidencias",
    "Servei per carretera": "Servicio por carretera",
    "Sense trens": "Sin trenes",
    "Bellaterra i Universitat Autònoma": "Bellaterra y Universitat Autònoma",
    "Fora d\u2019horari": "Fuera de horario",
    "Sense dades": "Sin datos",
    "Dades parcials": "Datos parciales",
    "extrem": "extremo",
    "molt alt": "muy alto",
    "alt": "alto",
    "moderat": "moderado",
  },
  // El text d'un risc (riscos.py el fa en català): la previsió i el que es mesura.
  riscos: {
    pluja_1h: ['Lluvia muy fuerte prevista: hasta {v} mm en una hora, {q}.', 'Ahora llueve muy fuerte: {v} mm en la última hora.'],
    pluja_12h: ['Mucha lluvia prevista: {v} mm en 12 horas, {q}.', 'Ha llovido mucho: {v} mm en las últimas 12 horas.'],
    ratxa: ['Viento muy fuerte previsto: rachas de hasta {v} km/h, {q}.', null],
    calor: ['Calor extremo previsto: hasta {v} °C, {q}.', 'Ahora hace calor extremo: {v} °C.'],
    fred: ['Frío intenso previsto: hasta {v} °C, {q}.', 'Ahora hace frío intenso: {v} °C.'],
    neu_24h: ['Nieve prevista: {v} cm en las próximas 24 horas.', null],
  },
  risc(r) {
    const plantilla = (this.riscos[r.tipus] || [])[r.origen === 'previsio' ? 0 : 1];
    if (!plantilla) return r.text;
    let quan = '';
    if (r.des_de && r.fins) {
      const ini = new Date(r.des_de);
      const dies = Math.round((new Date(ini).setHours(0, 0, 0, 0) - new Date().setHours(0, 0, 0, 0)) / 864e5);
      const dia = dies === 0 ? 'hoy' : dies === 1 ? 'mañana'
        : `${String(ini.getDate()).padStart(2, '0')}/${String(ini.getMonth() + 1).padStart(2, '0')}`;
      quan = `${dia} de ${ini.getHours()} a ${new Date(r.fins).getHours()} h`;
    }
    return plantilla.replace('{v}', Number(r.valor).toFixed(0).replace('-', '\u2212')).replace('{q}', quan);
  },
};
